:concurrency: 3
:timeout: 60
:verbose: true
:queues:
  - critical
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge
tasks: &tasks
  DailyPurchaseReportJob:
    cron: "0 0 * * *"
    queue: default
    description: "Generates daily purchase reports"
:scheduler:
  :schedule:
    <<: *tasks